### ISSUE TITLE
Scrollable dashboards

### ISSUE THREAD

**Issue by Jenskuin04** [OlegWock/anori#146]
The option to scroll in dashboards.
For less important information it would be handy to add more underneath the primary information!

**Comment by OlegWock** [comment]
Hello! This should be fixed in version 1.17.0. I'll upload it to stores today, but it will take a few more days to get it published. After update you should be able to drag widgets outside of visible grid, this will expand grid and enable scroll. 

Please note that when moving widget, at least one block of it should be in visible grid (e.g. you can't move widget out of screen right away, you'll need to do it in a few steps). This is technical limitation right now, I might be able to do something with it, but it will be in one of next versions
